DROP TABLE IF EXISTS equipment_models, equipment_types, equipment_lines CASCADE;

create table IF NOT EXISTS equipment_types
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
);


create table IF NOT EXISTS equipment_lines
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                varchar(100),
    country             varchar(50),
    brand               varchar(100),
    is_available_online boolean,
    is_in_instalment    boolean,
    type_id             BIGINT REFERENCES equipment_types (id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS equipment_models
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100),
    colour           VARCHAR(50),
    size             DOUBLE PRECISION,
    price            DOUBLE PRECISION,
    is_available     BOOLEAN,
    line_id          BIGINT REFERENCES equipment_lines (id),
    type_id          BIGINT REFERENCES equipment_types (id),
    pc_category      VARCHAR(100),
    processor        VARCHAR(100),
    memory           INTEGER,
    camera_count     INTEGER,
    collector_volume DOUBLE PRECISION,
    regime_count     INTEGER,
    category         VARCHAR(100),
    technology       VARCHAR(100),
    doors            INTEGER,
    compressor       VARCHAR(100)
);
-- Добавили все виды техники
INSERT INTO equipment_types(name)
VALUES ('smartphone'),
       ('refrigerator'),
       ('tv'),
       ('pc'),
       ('vacuum cleaner');

-- Добавили линейки телефонов
INSERT INTO equipment_lines(name, country, brand, is_available_online, is_in_instalment, type_id)
VALUES ('IOS', 'USA', 'Apple', true, true, (SELECT id FROM equipment_types WHERE name = 'smartphone')),
       ('Android', 'China', 'Xiaomi', true, true, (SELECT id FROM equipment_types WHERE name = 'smartphone'));

-- Добавили модели к каждой линейке телефонов
INSERT INTO equipment_models(name, colour, size, price, is_available, line_id, type_id, memory, camera_count)
VALUES ('Iphone X', 'black', 16.1, 100000.0, true, (SELECT id FROM equipment_lines WHERE name = 'IOS'),
        (SELECT id FROM equipment_types WHERE name = 'smartphone'), 256, 2),
       ('Iphone X', 'red', 10.0, 80000.0, true, (SELECT id FROM equipment_lines WHERE name = 'IOS'),
        (SELECT id FROM equipment_types WHERE name = 'smartphone'), 64, 2),
       ('Redmi 3', 'white', 10.0, 50000.0, true, (SELECT id FROM equipment_lines WHERE name = 'Android'),
        (SELECT id FROM equipment_types WHERE name = 'smartphone'), 128, 3),
       ('Note PRO', 'red', 10.0, 45000.0, false, (SELECT id FROM equipment_lines WHERE name = 'Android'),
        (SELECT id FROM equipment_types WHERE name = 'smartphone'), 128, 2);

-- Добавили линейки компьютеров
INSERT INTO equipment_lines(name, country, brand, is_available_online, is_in_instalment, type_id)
VALUES ('Mac', 'USA', 'Apple', true, true, (SELECT id FROM equipment_types WHERE name = 'pc')),
       ('Windows', 'USA', 'Microsoft', true, true, (SELECT id FROM equipment_types WHERE name = 'pc'));

-- Добавили модели к каждой линейке компьютеров
INSERT INTO equipment_models(name, colour, size, price, is_available, line_id, type_id, pc_category, processor)
VALUES ('MacBook Air', 'black', 20.0, 200000.0, true, (SELECT id FROM equipment_lines WHERE name = 'Mac'),
        (SELECT id FROM equipment_types WHERE name = 'pc'), 'laptop', 'intel'),
       ('Acer', 'grey', 17.0, 85000.0, true, (SELECT id FROM equipment_lines WHERE name = 'Windows'),
        (SELECT id FROM equipment_types WHERE name = 'pc'), 'notebook',
        'amd');
